### ISSUE TITLE
hello there..

### ISSUE THREAD

**Issue by vikvish** [juliangarnier/3D-CSS-Solar-System#1]
hello , i was just trying to create an .apk of your solar example but problem is that after creating an .apk installer and install on my tablet the application runing but no any images was displaying. 
you can check your example on chrome too. 
how can we run in tablet after creating an .apk installer file a "app installer for tablet".

with regards
vikram

**Comment by juliangarnier** [comment]
First, I have no knowledge in ".apk" package or anything related to Android development.
Second, your question is not very clear.
But if you have graphical issues on chrome on your tablet, it probably means that the hardware is not powerful enough.
