### ISSUE TITLE
Rotate around its own axis

### ISSUE THREAD

**Issue by M4N0JKUM4R** [juliangarnier/3D-CSS-Solar-System#4]
Can you try to recreate the solar system by having the planets rotate around its own axis? Currently it is orbiting the sun without the spin. I am trying to create a spherical ball rotation by adapting your method, if you find any.

Thanks!

**Comment by richrd** [comment]
How about this: http://codepen.io/donovanh/pen/GBIiv

**Comment by M4N0JKUM4R** [comment]
Wow! That is a really good approach, Richard! :+1:
